### ISSUE TITLE
Players are unable to respawn, they get disconnected with Internal server error

### ISSUE THREAD

**Issue by Polyana-Fontes** [wildex999/TickDynamic#27]
I left the mod running for few hours, it was running super fine, but many players started to create topics informing that they couldn't respawn.

This is that they see:
![image](https://cloud.githubusercontent.com/assets/3679022/13035018/be449ba6-d323-11e5-971d-630e0f81a9c3.png)

I captured this screenshot when I killed myself to attempt respawn:
![image](https://cloud.githubusercontent.com/assets/3679022/13035013/8d1a7f32-d323-11e5-8526-1b636e3f2bab.png)

It normalized after I removed the mod.

This was the last config file that I was testing:
https://gist.github.com/joserobjr/155403adacbdcaf2a01a

I tested with "TickDynamic - KCauldron 1.7.10-1614.193 - 0.2.0 Dev3" on KCauldron "version 1.7.10-1614.199"

**Comment by wildex999** [comment]
Thank you for taking the time to report the issue =)

Are you running the latest "dev3" version? I had hoped that all Entity desync issues was fixed in that.
It seems that it fails to remove the player entities, and thus will have problems adding them back in for respawning.

Which version of KCauldron are you running?

Does running the command "/tickdynamic reloadgroups" fix the issue when it happens?

**Comment by Polyana-Fontes** [comment]
Yes, I read on the description about the entity desync issue, but it happened with player entities. I'm going to do this test in few hours because I just restarted the server (I wasn't expecting a fast reply :P)

> Which version of KCauldron are you running?
> 1.7.10-1614.199

**Comment by wildex999** [comment]
Players exist in the World Entity list like any other, but they might be removed in a way I'm not correctly detecting. If so, I'll have to look more into it.

**Comment by wildex999** [comment]
Maybe also try setting 'debug = true' in the TickDynamic config. This will be a bit spammy in the console, but it might point out a clue to why this happens.

**Comment by Polyana-Fontes** [comment]
I just an small test with debug=true on my closed-beta server,
What I did:
- started it with the mod
- joined in
- used /fly and flew very high
- disabled /fly to die for fall damage

When I died this started to show repetitively on the console:

``` java
[19:27:17] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:17] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:17] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:17] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:17] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:17] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:17] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
```

When I clicked on respawn button I got disconnected and this was logged on the console:

``` java
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Entity removal desync! EntityPlayerMP['joserobjr'/1644, l='world', x=301,37, y=69,00, z=909,39](joserobjr at 301.3683165178465,69.0,909.3877337764019)
[19:27:18] [Server thread/WARN]: Failed to handle packet for /191.250.85.182:51679
org.apache.commons.lang3.NotImplementedException: indexOf is not implemented in TickDynamic''s List implementation!
    at com.wildex999.tickdynamic.listinject.ListManager.indexOf(ListManager.java:321) ~[tickdynamic-kcauldron1.7.10-10.13.2.1291-0.2.0-dev3.jar:?]
    at net.minecraft.world.World.func_72973_f(World.java:1890) ~[ahb.class:?]
    at net.minecraft.server.management.ServerConfigurationManager.respawnPlayer(ServerConfigurationManager.java:712) ~[oi.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147342_a(NetHandlerPlayServer.java:1615) ~[nh.class:?]
    at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:50) ~[is.class:?]
    at net.minecraft.network.play.client.C16PacketClientStatus.func_148833_a(SourceFile:8) ~[is.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[19:27:18] [Server thread/WARN]: Trying to remove: net.minecraft.tileentity.TileEntitySign@61c2df10 but does not belong to list: com.wildex999.tickdynamic.listinject.ListManagerTileEntities@f56acd but instead None
[19:27:18] [Server thread/WARN]: Trying to remove: net.minecraft.tileentity.TileEntityEndPortal@435cf095 but does not belong to list: com.wildex999.tickdynamic.listinject.ListManagerTileEntities@f56acd but instead None
/// --- literaly thousands of similar error messages "Trying to remove: %s but instead None"
[19:27:18] [Server thread/INFO]: joserobjr lost connection: Internal server error
/// --- many more messages "Trying to remove..."
[19:27:18] [Server thread/WARN]: Trying to remove: TileMultipart_cmp$$10@15799244 but does not belong to list: com.wildex999.tickdynamic.listinject.ListManagerTileEntities@f56acd but instead None
```

I'm temporarily hosting the full log of this test at http://gamemods.com.br/latest.log , please save it privately and notify me because I don't feel super-safe exposing all that log data, so I'll remove it as soon as you notify me.

**Comment by wildex999** [comment]
Thank you for the log, the information actually tells me quite a bit =)

Looking through the log file, there seems to be 3 problems:
1. TileEntities are not correctly registered as belonging to the Injected list.
2. Players are not correctly removed from EntityList.
3. respawnPlayer tries to call a method I apparently have not implemented(THis cuases the respawn to fail).

I will take a look at this over the weekend, thank you for taking the time to post =)

**Comment by wildex999** [comment]
Have looked over it now.
- The TileEntity spam was just an error with the debugging message. It should really have been saying that the TileEntity does not exist in list, which is ok as some TileEntities checks for it's existence before adding to the list.
- Player removal desync was a very specific problem which happens only when the Entity being removed is the last to tick, as it then thinks the list is empty due to how TickDynamic works.
- Implementing the IndexOf method fixed the respawn problem.

This should all now be fixed with release dev4. =)
